apiVersion: v1
kind: Service
metadata:
  name: p2p-bootnode
  labels:
    app: p2p-node
    role: bootnode
spec:
  type: LoadBalancer
  ports:
  - port: 32221
    targetPort: 32221
    name: gossip
    protocol: TCP
  selector:
    app: p2p-node
    role: bootnode
