apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p-bootnode
  labels:
    app: p2p-node
    role: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2p-node
      role: bootnode
  template:
    metadata:
      labels:
        app: p2p-node
        role: bootnode
    spec:
      containers:
        - name: bootnode
          image: yutongp/go-p2p:test
          imagePullPolicy: Always
          command: ["/go/src/github.com/zjshen14/go-p2p/bin/main"]
          args: ["-exthost=35.230.103.170", "-extport=32221"]
          ports:
          - containerPort: 32221
            protocol: TCP
          - name: metrics
            containerPort: 8080
            protocol: TCP
          env:
            - name: P2P_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
